### ISSUE TITLE
[CR] Improve "Show Total Cash Held" function

### ISSUE THREAD

**Issue by rongxin** [oscaraya/PT1_SCM_Workshop2#1]
### Current

On “Maintenance Panel”, the user (“Maintainer”) needs to click on each denomination to see the number of coins to be collected for each denomination. 

The user then needs to click on “Show Total Cash Held” to see the total cash amount to be collected. 
### Problem

It has been reported that it is possible that what the user collected does not match with the amount recorded in the system. The current screen is causing inconvenience and confusion to the user by forcing him to click buttons one by one for each denomination and manually calculate each amount. Moreover, the user needs to calculate the total number of coins collected, which becomes another source of error. 
## Changes needed

After pressing on “Show Total Cash Held” by the Maintainer, 
- the specific quantity of coins per denomination together with total cash amount for each denomination should be displayed. 
- the total number of coins should be displayed beside the total cash amount
## Development Notes
- Changes to be pushed to following _feature branch_, please check out the branch when start the task.
  `feature/CR1-TotalCashHeld`
- Specify the git issue number in the commit message:
  
  E.g.  `git commit -m "#1 | code changes details"`
- Perform the internal test and attach test result to the issue before pass to QA testing.
- Assign to tech lead when the implementation and internal testing are done.
### MaintenanceController.java
- Add functions to get amount for each denomination. 
### MaintenancePanel.java
- Change text "Quantity of Coins Available" to "Quantity" to leave more space. 
- Add new label "Coin Value" for indicating the coin value for each denomination.  
- Add new label "Amount" for indication the amount of coin for each denomination. 
- Add new fields on the right side of coin quantity for each denomination to display amount of coins. 
- Remove buttons which is used to display quantity of coins for each denomination after pressing. 
- Display quantity of coins for each denomination automatically. 
- Add the new field on the right side of total cash amount to display total quantity of collected coins.  
### TotalCashButtonListener.java
- Add functions to get total quantity of coins to collect.

**Comment by rongxin** [comment]
Assign to developer @LANXIANGMING to implement the changes.
Please read and understand the issue before starting implementation.
If there's any doubts, please raise here.

**Comment by LANXIANGMING** [comment]
Implemented and tested this CR, and pushed to branch "feature/CR1-TotalCashHeld". Please verify the CR implementation.

**Comment by LANXIANGMING** [comment]
Implemented and tested this CR, and pushed to branch "feature/CR1-TotalCashHeld". Please verify the CR implementation.

**Comment by rongxin** [comment]
@LANXIANGMING 
Thanks! Please attach internal testing result/screenshots to the issue ticket.

**Comment by LANXIANGMING** [comment]
![e0f1ee87-c8d4-4302-aaaa-b7d798782ecd](https://cloud.githubusercontent.com/assets/11241235/18544435/28693078-7b67-11e6-8b2b-ee0540320f84.jpg)

**Comment by rongxin** [comment]
@LANXIANGMING Thanks!
I have merged the codes from feature branch to develop branch.

@suhhgd I am passing this issue to you for QA testing.
Please pull latest codes from **develop** branch for the testing.

**Comment by suhhgd** [comment]
Verification done.. It is working as expected . Good Job .. @LANXIANGMING 

![ca4](https://cloud.githubusercontent.com/assets/11241099/18607938/f4133d48-7d0d-11e6-947c-34d49aca43e9.png)

**Comment by suhhgd** [comment]
Accidentally close the case. Reopen for @rongxin  review.

**Comment by rongxin** [comment]
Thanks @suhhgd !
I have done final verification, uploaded updated design documents.
I am closing this issue now.
