### ISSUE TITLE
[Defect] Amounts and Quantity are still displayed after logout

### ISSUE THREAD

**Issue by rongxin** [oscaraya/PT1_SCM_Workshop2#2]
### Current behaviour

On “Maintenance Panel”, 
the user (“Maintainer”) log out of the drinks dispenser machine, 
the amounts and quantity of coins displayed in _“Show Total Cash Held”_ and _“Collect Cash”_. 
### Expectation

After pressing on “Press to Collect All Cash” by the Maintainer, 
- the total amount of “Total Cash Held” coins should be rest to null. 
- the total quantity of “Total Cash Held” coins should be rest to null. After pressing on “Press Here when Finished” by the Maintainer, 
- the total quantity of “Collect Cash” coins should be rest to null.
## Development Notes
- Please checkout feature branch feature/defect-AmountAndQuantityAfterLogout and start the fix.
- Mention the issue number in the commit message.
  e.g. `git commit -m "#2 | fix the defect"`
- Perform internal testing and attach test result before assign to QA for testing.

**Comment by rongxin** [comment]
@LokeshKB Please investigate the defect and fix it.

**Comment by LokeshKB** [comment]
@rongxin Fixed the defect and pushed to feature branch, please merge it to develop branch.
@suhhgd fixed #2 in feature branch, You can start verifying after rongxin merges to develop branch. attached the screenshots as well. Thanks.
[Defect#2UnitTest.docx](https://github.com/oscaraya/PT1_SCM_Workshop2/files/478581/Defect.2UnitTest.docx)

**Comment by rongxin** [comment]
@LokeshKB Thanks!
I have merged the feature branch to develop branch, and @suhhgd can do the testing on develop branch now.

**Comment by suhhgd** [comment]
Hi @rongxin I have verified and it is working as per expectation state. 

1) Set the available coin value.
![image](https://cloud.githubusercontent.com/assets/11241099/18664887/2802455e-7f57-11e6-84b8-b808fdde2e59.png)

2) The available coin value are displayed accordingly. 
![image](https://cloud.githubusercontent.com/assets/11241099/18664934/57f796a6-7f57-11e6-85df-5c740b30d3d1.png)

3) Press "Collect Cash"
![image](https://cloud.githubusercontent.com/assets/11241099/18664966/8386dba6-7f57-11e6-84ac-12a9c60d306a.png)

4) Then “Press Here when Finished" and activate the application again. the total amount of “Total Cash Held” coins reset to null. 
![image](https://cloud.githubusercontent.com/assets/11241099/18664841/f62974d0-7f56-11e6-91d8-08c47bde1bc8.png)

**Comment by rongxin** [comment]
Thanks @suhhgd 
I have done final verification and will close this issue now.
